name: WorkFlow filters check

on: 
  workflow_dispatch: 

  push: 
    branches: 
      - main
      - '!feature/*'

  pull_request: 
    types: 
      - opened
      - closed
    paths-ignore: 
      - README.md
    branches: 
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Event Name 
        run: echo this workflow/job/step is executed for event type ${{github.event_name}}

      - name: Check env name
        run: echo ${{vars.CF_USERNAME}}
